[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "script-src 'strict-dynamic' https://gc.zgo.at; object-src 'none'; connect-src https://stvfrnzl.goatcounter.com/count"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "geolocation=(), camera=(), microphone=()"
