import type { NextPage } from 'next'
import Head from 'next/head'
import Intro from '@components/Intro'
import Portfolio from '@components/Portfolio'
import Contact from '@components/Contact'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Steve Frenzel | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Add skip link */}
      <Intro />
      <main>
        <Portfolio />
        <Contact />
      </main>
    </>
  )
}

export default Home
